### ISSUE TITLE
Partner with us section needed on Collect data page or home page

### ISSUE THREAD

**Issue by chicksim** [coronasafe/life#39] opened 2021-04-23 22:32 UTC
How about a 'Partner/Collaborate with Us' icon or section on the home page. This is priority as any initiative if it lands our home page will know that we are actively looking for partners to share data! Not sure about the visualisation of it though. plz recommend ideas?

_Content is below:_ 

### Are you a similar initiative like ours? or know one?
Run by your company, friends, college, on social media that has similar data. Reach out to them, talk about us. Earnest request to get other initiatives to collaborate as consolidation is important in the problem that we are solving. We dont seek credits, we just want this information to reach. Our goal is to provide the right information to the right people at the right time in the right manner. POC- Simran, Pranshumaan, Ajay

This is a product of collaboration - covidfyi, a swasth initiative, backed by coronasafe, with stepone volunteers, PIIndia, medical support group, Indian helpline, InsideIIM, IIM-K community support (many more).

**Comment by karmakoder** [comment] 2021-04-23 22:39
+1 for this. Wondering what wud be call to action and where wud it lead a user? Do we have manpower to give this to a group within life? That group gets on a call or chat wid anyone who avails this and guides them to volunteer for some area of life?

**Comment by bodhish** [comment] 2021-04-24 04:57
This looks like a duplicate issue. Already addressed in about

**Comment by Deep-Codes** [comment] 2021-04-24 11:07
Duplicate of #60? Then Close this

**Comment by chicksim** [comment] 2021-04-27 23:12
Hi we need to reopen this issue - We need a separate partner with us page that will have both - Content and Partners logos. Sharing content below. For now this is the content to give you an idea: (also can someone open this issue again? )

Heading: Partner with us
Body: Citizen's groups and civil society organisations providing Covid Relief have formed 'Covid Relief India Alliance'. The goal is to consolidate our efforts and provide relief to the remotest region of India with equal rigour. The group has 15+ projects collaborating already. If you know a citizen or an organisation running Covid Relief Projects, ask them to join forces! Fill up this form and one of our volunteers will reach out to you soon! 

CTA button: https://forms.gle/mipGNhsuVFXWiTGG6 

(@karmakoder - this team can handle the onboarding workflow)


[Unified Backend Partnership_Covid19 Citizens Alliance (5).pdf](https://github.com/coronasafe/life/files/6388145/Unified.Backend.Partnership_Covid19.Citizens.Alliance.5.pdf) - this file is to be updated. But for now go ahead and use this.

**Comment by chicksim** [comment] 2021-04-27 23:15
Partner names: 

PIIndia.org, StepOne, Indiacovidresources.in - please take their logos and names from their site or google. This list will keep adding. so it will keep increasing. I ll keep posting here may be?

**Comment by peeyush14goyal** [comment] 2021-04-28 04:12
We also have a separate page /partners showing current partners we can make changes to that

**Comment by divyagar** [comment] 2021-04-28 04:16
Yeah I am making changes on that page only.

**Closed** 2021-04-28 07:49 UTC
Labels: enhancement
