### ISSUE TITLE
Add location based features

### ISSUE THREAD

**Issue by shubhabrataroy** [coronasafe/life#170] opened 2021-04-27 20:37 UTC
Help finding resource based on users location. Example: If I keep my location turned on it would show my nearby facilities.

**Comment by Deep-Codes** [comment] 2021-04-27 20:48
> Help finding resource based on users location. Example: If I keep my location turned on it would show my nearby facilities.

Duplicate of #157 ?

**Comment by shubhabrataroy** [comment] 2021-04-27 22:17
> > Help finding resource based on users location. Example: If I keep my location turned on it would show my nearby facilities.
> 
> Duplicate of #157 ?

Not fully, but yes they have some similarity. Geolocation + search based on geolocation.

**Comment by vandanabhandari** [comment] 2021-04-28 13:13
looks like a lot of usage to geolocation integration. I was looking at a similar one but have not started. https://github.com/coronasafe/life/issues/136

**Comment by karmakoder** [comment] 2021-04-30 14:36
> @karmakoder @shubhabrataroy I think this should be combined with #157 and #136, they're similar enough I think.

Agreed. @shubhabrataroy lets plz combine efforts under https://github.com/coronasafe/life/issues/136. I'll intro u to the dev who is working on part of this problem.

**Closed by karmakoder** 2021-04-30 14:36 UTC
